package dao;
// Generated 16/08/2020 04:53:52 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private int id;
	private String nombre;
	private int edad;
	private String estadoCivil;
	private Set usuarios = new HashSet(0);

	public Persona() {
	}

	public Persona(int id, String nombre, int edad, String estadoCivil) {
		this.id = id;
		this.nombre = nombre;
		this.edad = edad;
		this.estadoCivil = estadoCivil;
	}

	public Persona(int id, String nombre, int edad, String estadoCivil, Set usuarios) {
		this.id = id;
		this.nombre = nombre;
		this.edad = edad;
		this.estadoCivil = estadoCivil;
		this.usuarios = usuarios;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
