package dao;
// Generated 16/08/2020 04:53:52 PM by Hibernate Tools 3.5.0.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int id;
	private Persona persona;
	private String correo;
	private String contrasena;

	public Usuario() {
	}

	public Usuario(int id, Persona persona, String correo, String contrasena) {
		this.id = id;
		this.persona = persona;
		this.correo = correo;
		this.contrasena = contrasena;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
